version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: tvb_charity_db
    ports:
      - "3306:3306"

  web1:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db

  web2:
    build: .
    ports:
      - "5002:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db